name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3

      - name: 'Install dependencies'
        run: |
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: 'Update Submodules'
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: 'Configure'
        run: |
          mkdir -p build
          cmake -B build

      - name: 'Build'
        run: |
          make -C build

      - name: 'Upload binary'
        uses: actions/upload-artifact@v3
        with:
          name: pico-uart-bridge.uf2
          path: build/uart_bridge.uf2
          retention-days: 5
